#!/bin/sh
set -u
set -e

# Check that $ROOT/remaster/{isolinux/*.cfg boot/grub/*.cfg} say Bio-Linux 8
# and not Ubuntu.

#VERSION should be exported by recon
BLVERS="`echo "$VERSION" | cut -d. -f1`"
[ -z "$BLVERS" ] && BLVERS=8

echo
echo "Verifying bootup branding in isolinux/ and boot/grub/"

if [ -z "${ROOT:-}" ] ; then
    echo '!'" \$ROOT is not set.  Can't continue"
    exit 1
fi

cd "${ROOT}/remaster"
tofix="`grep -E 'Ubuntu | integrity-check quiet | integrity-check iso-scan/filename=\${iso_path} quiet splash | integrity-check initrd=/casper/initrd.lz quiet splash' isolinux/*.cfg boot/grub/*.cfg isolinux/f1.txt | wc -l`"
if [ "$tofix" = 0 ] ; then
    echo ". Looks good"
    exit 0
fi

for f in isolinux/*.cfg boot/grub/*.cfg isolinux/f1.txt ; do 
    sed -i -e 's/Ubuntu\( [0-9.]\{5\}\)\?/Bio-Linux '"$BLVERS/"\
    -e 's?integrity-check quiet splash?integrity-check quiet?'\
    -e 's?integrity-check iso-scan/filename=\${iso_path} quiet splash?integrity-check iso-scan/filename=\${iso_path} quiet?'\
    -e 's?integrity-check initrd=/casper/initrd.lz quiet splash?integrity-check initrd=/casper/initrd.lz quiet?' "$f"
done
echo "~ Fixed $tofix lines."
