#!/bin/sh
set -u
set -e

echo
echo "Checking only one kernel_headers package is installed..."

# if [ -z "${ROOT:-}" ] ; then
#     echo '!'" \$ROOT is not set.  Can't continue"
#     exit 1
# fi

if [ ! -x ~/bl8bits/bin/openchroot ] ; then
    echo '!'" No executable ~/bl8bits/bin/openchroot.  Can't continue"
    exit 1
fi

[ `echo 'dpkg -l' | ~/bl8bits/bin/openchroot | grep linux-headers- | wc -l` = 3 ]
